### PR TITLE
ammo_ar2.lua

### PR DESCRIPTION
**Pull request by williamgiddings**
Can't seem to find the issue with the ammo equiping

### CODE REVIEW

**Comment by whathe12** [comment]
For some reason the ar2 ammo is fine and can be equipped from the inventory, but the other ammunition cannot be equipped for some reason.

**Comment by williamgiddings** [comment]
There wasn't any other ammunition in the items list when I checked earlier.
What ammo are you equipping?
The only one I see is AR2

## 

## 

Will Giddings, CEO
GalacticCat Interactive

**Comment by CaveeJohnson** [comment]
ar2 is not upper-case and other weapons use ar2 ammo type, why pr this?

**Comment by whathe12** [comment]
In the screenshot I sent you can see all the ammo except for the ar2 ammo in the inventory doesn't have the option to be equipped, dropped, etc. It's my most recent screenshot on my steam.

**Comment by whathe12** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=678707272

**Comment by CaveeJohnson** [comment]
That is nothing to do with this pull request, this doesn't fix anything it only changes strings

**Comment by CaveeJohnson** [comment]
I would need to see the ammo files you created to figure out what is going on, but I know for a fact that this is not a fix

**Comment by williamgiddings** [comment]
I haven't added any ammo types. The only one in the game is the ar2 ammo
currently. What weapons are you trying to use?

## 

## 

Will Giddings, CEO
GalacticCat Interactive

**Comment by williamgiddings** [comment]
Have you guys got TeamSpeak or Mumble or anything. Might be easier to all
talk about the issues.
Maybe we could set up a Trello roadmap too?

## 

## 

Will Giddings, CEO
GalacticCat Interactive

**Comment by whathe12** [comment]
Yep, I have a TS server and a discord we could use.

**Comment by williamgiddings** [comment]
May I have the IP for both? I can't talk tonight but tomorrow I will (UK
time)

## 

## 

Will Giddings, CEO
GalacticCat Interactive

**Comment by whathe12** [comment]
http://home.bluedrake42.com/ click on the discord tab for the discord then goto the Garry's Mod channel and     dkb.ts.nfoservers.com is the ts server

**Comment by williamgiddings** [comment]
Great. Thank you.
I have found a different weapons pack we can use. Its a very small download
and uses c_ view models

## 

## 

Will Giddings, CEO
GalacticCat Interactive

**Pull request closed without merging**
